#!/bin/bash
# Generated by pych-gui

export PYCH_CORE_WORK='config'
export REMOTE_ADDR='raspberrypi.local'
export REMOTE_USER='pi'
export REMOTE_WORK='/home/pi/core'
export REMOTE_ARCH='aarch64-unknown-linux-gnu'
export REMOTE_LOCAL='/home/inception/Downloads/ll'
export REMOTE_SSH_KEY='/home/inception/git/pych/ssh/id_rsa'
export EXTERNAL_PLUGIN_PATH='['/home/inception/git/pych_plugins']'

export REMOTE_SSH_ARGS="-i ${REMOTE_SSH_KEY} "
export REMOTE_SSH="${REMOTE_USER}@${REMOTE_ADDR}" 
export REMOTE_TTY="ssh $REMOTE_SSH_ARGS $REMOTE_SSH" 

export LD_LIBRARY_PATH=lib/:${LD_LIBRARY_PATH} 

export PYCH_CORE_ACTIVATED="1" 
export PYCH_NAME="core"
export PS1='($(echo $PYCH_NAME))\[\e[1;32m\]\u@\h:\[\e[1;34m\]\w\[\e[0m\]\$ ' 

echo "PYCH (Activated)"
