#!/bin/bash
# Generated by pych-gui

export PYCH_ACTIVATE_SH='/home/inception/git/pych-gui/config/activate.sh'

export PYCH_CORE_WORK='/home/inception/git/pych'
export REMOTE_ADDR='127.0.0.1'
export REMOTE_USER='inception'
export REMOTE_WORK='/home/inception/Downloads/ll0'
export REMOTE_ARCH='x86_64-linux-gnu'
export REMOTE_LOCAL='/home/inception/Downloads/ll'
export REMOTE_SSH_KEY='/home/inception/git/pych/ssh/id_rsa'
export REMOTE_PYCH_BIN='testCore'
export REMOTE_MODEL_PATH='ScienceMode3.json'
export EXTERNAL_PLUGIN_PATH='['/home/inception/git/pych_plugins']'

export REMOTE_SSH_ARGS="-i ${REMOTE_SSH_KEY} "
export REMOTE_SSH="${REMOTE_USER}@${REMOTE_ADDR}" 
export REMOTE_TTY="ssh $REMOTE_SSH_ARGS $REMOTE_SSH" 

export LD_LIBRARY_PATH=lib/:${LD_LIBRARY_PATH} 

export PYCH_CORE_ACTIVATED="1" 
export PYCH_NAME="core"
export PS1='($(echo $PYCH_NAME))\[\e[1;32m\]\u@\h:\[\e[1;34m\]\w\[\e[0m\]\$ ' 

echo "PYCH (Activated)"
